package com.beiyelin.service.footstone.model;

import java.util.Date;

public class Organization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.ID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.ParentID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.Code
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.Name
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.Type
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.Address
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.UserID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.ArtificialPerson2
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String artificialperson2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.ArtificalID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String artificalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.ArtificalMobile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String artificalmobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.ArtificalIDFile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String artificalidfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.ManagerName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String managername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.ManagerID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String managerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.ManagerMobile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String managermobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.ManagerIDFile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String manageridfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.CreateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.Updater
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.UpdateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.Audited
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Boolean audited;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.Status
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.Name2
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String name2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.OrgCode
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String orgcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.BusinessLicense
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String businesslicense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.ArtificialPerson
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String artificialperson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.BusinessScope
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String businessscope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.LicenseScope
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String licensescope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.Size
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.BankAccountName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String bankaccountname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.BankName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String bankname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.BankAccount
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String bankaccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.OrgCodeFile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String orgcodefile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.BusinessLicenseFile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String businesslicensefile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.RigisterFile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String rigisterfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frorg.ApprovalFile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String approvalfile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.ID
     *
     * @return the value of frorg.ID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.ID
     *
     * @param id the value for frorg.ID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.ParentID
     *
     * @return the value of frorg.ParentID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.ParentID
     *
     * @param parentid the value for frorg.ParentID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.Code
     *
     * @return the value of frorg.Code
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.Code
     *
     * @param code the value for frorg.Code
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.Name
     *
     * @return the value of frorg.Name
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.Name
     *
     * @param name the value for frorg.Name
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.Type
     *
     * @return the value of frorg.Type
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.Type
     *
     * @param type the value for frorg.Type
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.Address
     *
     * @return the value of frorg.Address
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.Address
     *
     * @param address the value for frorg.Address
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.UserID
     *
     * @return the value of frorg.UserID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.UserID
     *
     * @param userid the value for frorg.UserID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.ArtificialPerson2
     *
     * @return the value of frorg.ArtificialPerson2
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getArtificialperson2() {
        return artificialperson2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.ArtificialPerson2
     *
     * @param artificialperson2 the value for frorg.ArtificialPerson2
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setArtificialperson2(String artificialperson2) {
        this.artificialperson2 = artificialperson2 == null ? null : artificialperson2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.ArtificalID
     *
     * @return the value of frorg.ArtificalID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getArtificalid() {
        return artificalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.ArtificalID
     *
     * @param artificalid the value for frorg.ArtificalID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setArtificalid(String artificalid) {
        this.artificalid = artificalid == null ? null : artificalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.ArtificalMobile
     *
     * @return the value of frorg.ArtificalMobile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getArtificalmobile() {
        return artificalmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.ArtificalMobile
     *
     * @param artificalmobile the value for frorg.ArtificalMobile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setArtificalmobile(String artificalmobile) {
        this.artificalmobile = artificalmobile == null ? null : artificalmobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.ArtificalIDFile
     *
     * @return the value of frorg.ArtificalIDFile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getArtificalidfile() {
        return artificalidfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.ArtificalIDFile
     *
     * @param artificalidfile the value for frorg.ArtificalIDFile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setArtificalidfile(String artificalidfile) {
        this.artificalidfile = artificalidfile == null ? null : artificalidfile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.ManagerName
     *
     * @return the value of frorg.ManagerName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getManagername() {
        return managername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.ManagerName
     *
     * @param managername the value for frorg.ManagerName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setManagername(String managername) {
        this.managername = managername == null ? null : managername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.ManagerID
     *
     * @return the value of frorg.ManagerID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getManagerid() {
        return managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.ManagerID
     *
     * @param managerid the value for frorg.ManagerID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setManagerid(String managerid) {
        this.managerid = managerid == null ? null : managerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.ManagerMobile
     *
     * @return the value of frorg.ManagerMobile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getManagermobile() {
        return managermobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.ManagerMobile
     *
     * @param managermobile the value for frorg.ManagerMobile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setManagermobile(String managermobile) {
        this.managermobile = managermobile == null ? null : managermobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.ManagerIDFile
     *
     * @return the value of frorg.ManagerIDFile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getManageridfile() {
        return manageridfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.ManagerIDFile
     *
     * @param manageridfile the value for frorg.ManagerIDFile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setManageridfile(String manageridfile) {
        this.manageridfile = manageridfile == null ? null : manageridfile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.CreateTime
     *
     * @return the value of frorg.CreateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.CreateTime
     *
     * @param createtime the value for frorg.CreateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.Updater
     *
     * @return the value of frorg.Updater
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.Updater
     *
     * @param updater the value for frorg.Updater
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.UpdateTime
     *
     * @return the value of frorg.UpdateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.UpdateTime
     *
     * @param updatetime the value for frorg.UpdateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.Audited
     *
     * @return the value of frorg.Audited
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Boolean getAudited() {
        return audited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.Audited
     *
     * @param audited the value for frorg.Audited
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setAudited(Boolean audited) {
        this.audited = audited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.Status
     *
     * @return the value of frorg.Status
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.Status
     *
     * @param status the value for frorg.Status
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.Name2
     *
     * @return the value of frorg.Name2
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getName2() {
        return name2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.Name2
     *
     * @param name2 the value for frorg.Name2
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setName2(String name2) {
        this.name2 = name2 == null ? null : name2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.OrgCode
     *
     * @return the value of frorg.OrgCode
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getOrgcode() {
        return orgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.OrgCode
     *
     * @param orgcode the value for frorg.OrgCode
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode == null ? null : orgcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.BusinessLicense
     *
     * @return the value of frorg.BusinessLicense
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getBusinesslicense() {
        return businesslicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.BusinessLicense
     *
     * @param businesslicense the value for frorg.BusinessLicense
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setBusinesslicense(String businesslicense) {
        this.businesslicense = businesslicense == null ? null : businesslicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.ArtificialPerson
     *
     * @return the value of frorg.ArtificialPerson
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getArtificialperson() {
        return artificialperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.ArtificialPerson
     *
     * @param artificialperson the value for frorg.ArtificialPerson
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setArtificialperson(String artificialperson) {
        this.artificialperson = artificialperson == null ? null : artificialperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.BusinessScope
     *
     * @return the value of frorg.BusinessScope
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getBusinessscope() {
        return businessscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.BusinessScope
     *
     * @param businessscope the value for frorg.BusinessScope
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setBusinessscope(String businessscope) {
        this.businessscope = businessscope == null ? null : businessscope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.LicenseScope
     *
     * @return the value of frorg.LicenseScope
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getLicensescope() {
        return licensescope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.LicenseScope
     *
     * @param licensescope the value for frorg.LicenseScope
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setLicensescope(String licensescope) {
        this.licensescope = licensescope == null ? null : licensescope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.Size
     *
     * @return the value of frorg.Size
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.Size
     *
     * @param size the value for frorg.Size
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.BankAccountName
     *
     * @return the value of frorg.BankAccountName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getBankaccountname() {
        return bankaccountname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.BankAccountName
     *
     * @param bankaccountname the value for frorg.BankAccountName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setBankaccountname(String bankaccountname) {
        this.bankaccountname = bankaccountname == null ? null : bankaccountname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.BankName
     *
     * @return the value of frorg.BankName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.BankName
     *
     * @param bankname the value for frorg.BankName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.BankAccount
     *
     * @return the value of frorg.BankAccount
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getBankaccount() {
        return bankaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.BankAccount
     *
     * @param bankaccount the value for frorg.BankAccount
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setBankaccount(String bankaccount) {
        this.bankaccount = bankaccount == null ? null : bankaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.OrgCodeFile
     *
     * @return the value of frorg.OrgCodeFile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getOrgcodefile() {
        return orgcodefile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.OrgCodeFile
     *
     * @param orgcodefile the value for frorg.OrgCodeFile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setOrgcodefile(String orgcodefile) {
        this.orgcodefile = orgcodefile == null ? null : orgcodefile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.BusinessLicenseFile
     *
     * @return the value of frorg.BusinessLicenseFile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getBusinesslicensefile() {
        return businesslicensefile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.BusinessLicenseFile
     *
     * @param businesslicensefile the value for frorg.BusinessLicenseFile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setBusinesslicensefile(String businesslicensefile) {
        this.businesslicensefile = businesslicensefile == null ? null : businesslicensefile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.RigisterFile
     *
     * @return the value of frorg.RigisterFile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getRigisterfile() {
        return rigisterfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.RigisterFile
     *
     * @param rigisterfile the value for frorg.RigisterFile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setRigisterfile(String rigisterfile) {
        this.rigisterfile = rigisterfile == null ? null : rigisterfile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frorg.ApprovalFile
     *
     * @return the value of frorg.ApprovalFile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getApprovalfile() {
        return approvalfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frorg.ApprovalFile
     *
     * @param approvalfile the value for frorg.ApprovalFile
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setApprovalfile(String approvalfile) {
        this.approvalfile = approvalfile == null ? null : approvalfile.trim();
    }
}