package com.beiyelin.service.footstone.model;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frpermission.ID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frpermission.ModuleID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String moduleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frpermission.Name
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frpermission.IsModule
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Boolean ismodule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frpermission.IsFunction
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Boolean isfunction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frpermission.IsField
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Boolean isfield;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frpermission.Description
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frpermission.ID
     *
     * @return the value of frpermission.ID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frpermission.ID
     *
     * @param id the value for frpermission.ID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frpermission.ModuleID
     *
     * @return the value of frpermission.ModuleID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getModuleid() {
        return moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frpermission.ModuleID
     *
     * @param moduleid the value for frpermission.ModuleID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setModuleid(String moduleid) {
        this.moduleid = moduleid == null ? null : moduleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frpermission.Name
     *
     * @return the value of frpermission.Name
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frpermission.Name
     *
     * @param name the value for frpermission.Name
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frpermission.IsModule
     *
     * @return the value of frpermission.IsModule
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Boolean getIsmodule() {
        return ismodule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frpermission.IsModule
     *
     * @param ismodule the value for frpermission.IsModule
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setIsmodule(Boolean ismodule) {
        this.ismodule = ismodule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frpermission.IsFunction
     *
     * @return the value of frpermission.IsFunction
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Boolean getIsfunction() {
        return isfunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frpermission.IsFunction
     *
     * @param isfunction the value for frpermission.IsFunction
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setIsfunction(Boolean isfunction) {
        this.isfunction = isfunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frpermission.IsField
     *
     * @return the value of frpermission.IsField
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Boolean getIsfield() {
        return isfield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frpermission.IsField
     *
     * @param isfield the value for frpermission.IsField
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setIsfield(Boolean isfield) {
        this.isfield = isfield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frpermission.Description
     *
     * @return the value of frpermission.Description
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frpermission.Description
     *
     * @param description the value for frpermission.Description
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}