package com.beiyelin.service.footstone.model;

import java.util.Date;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frrole.ID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frrole.SpaceID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String spaceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frrole.RoleCode
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String rolecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frrole.RoleName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frrole.Creator
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frrole.CreateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frrole.Updater
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frrole.UpdateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frrole.Status
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frrole.ID
     *
     * @return the value of frrole.ID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frrole.ID
     *
     * @param id the value for frrole.ID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frrole.SpaceID
     *
     * @return the value of frrole.SpaceID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getSpaceid() {
        return spaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frrole.SpaceID
     *
     * @param spaceid the value for frrole.SpaceID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setSpaceid(String spaceid) {
        this.spaceid = spaceid == null ? null : spaceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frrole.RoleCode
     *
     * @return the value of frrole.RoleCode
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frrole.RoleCode
     *
     * @param rolecode the value for frrole.RoleCode
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode == null ? null : rolecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frrole.RoleName
     *
     * @return the value of frrole.RoleName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frrole.RoleName
     *
     * @param rolename the value for frrole.RoleName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frrole.Creator
     *
     * @return the value of frrole.Creator
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frrole.Creator
     *
     * @param creator the value for frrole.Creator
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frrole.CreateTime
     *
     * @return the value of frrole.CreateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frrole.CreateTime
     *
     * @param createtime the value for frrole.CreateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frrole.Updater
     *
     * @return the value of frrole.Updater
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frrole.Updater
     *
     * @param updater the value for frrole.Updater
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frrole.UpdateTime
     *
     * @return the value of frrole.UpdateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frrole.UpdateTime
     *
     * @param updatetime the value for frrole.UpdateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frrole.Status
     *
     * @return the value of frrole.Status
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frrole.Status
     *
     * @param status the value for frrole.Status
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}