package com.beiyelin.service.footstone.model;

public class RolePermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frrolepermission.ID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frrolepermission.RoleID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column frrolepermission.PermissionID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String permissionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frrolepermission.ID
     *
     * @return the value of frrolepermission.ID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frrolepermission.ID
     *
     * @param id the value for frrolepermission.ID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frrolepermission.RoleID
     *
     * @return the value of frrolepermission.RoleID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frrolepermission.RoleID
     *
     * @param roleid the value for frrolepermission.RoleID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column frrolepermission.PermissionID
     *
     * @return the value of frrolepermission.PermissionID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getPermissionid() {
        return permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column frrolepermission.PermissionID
     *
     * @param permissionid the value for frrolepermission.PermissionID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setPermissionid(String permissionid) {
        this.permissionid = permissionid == null ? null : permissionid.trim();
    }
}