package com.beiyelin.service.footstone.model;

import java.util.Date;
import java.util.List;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.ID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.UserType
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Integer usertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.UserName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.TrueName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String truename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.NickName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Sex
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.EmployeeID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String employeeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.DepartmentID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String departmentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.CreateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Password
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Salt
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Activity
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Boolean activity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.EmailActivity
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Boolean emailactivity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.PhoneActivity
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Boolean phoneactivity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Email
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Phone
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Status
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.UpdateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Updater
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.AuditDate
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Date auditdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Audited
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Boolean audited;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Type
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.Number
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.FrontImage
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String frontimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.BackImage
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String backimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.DurDate
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private Date durdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.enFirstName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String enfirstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the footstone column fruser.enLastName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    private String enlastname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.ID
     *
     * @return the value of fruser.ID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.ID
     *
     * @param id the value for fruser.ID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.UserType
     *
     * @return the value of fruser.UserType
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Integer getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.UserType
     *
     * @param usertype the value for fruser.UserType
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.UserName
     *
     * @return the value of fruser.UserName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.UserName
     *
     * @param username the value for fruser.UserName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.TrueName
     *
     * @return the value of fruser.TrueName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.TrueName
     *
     * @param truename the value for fruser.TrueName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setTruename(String truename) {
        this.truename = truename == null ? null : truename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.NickName
     *
     * @return the value of fruser.NickName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.NickName
     *
     * @param nickname the value for fruser.NickName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Sex
     *
     * @return the value of fruser.Sex
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Sex
     *
     * @param sex the value for fruser.Sex
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.EmployeeID
     *
     * @return the value of fruser.EmployeeID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.EmployeeID
     *
     * @param employeeid the value for fruser.EmployeeID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid == null ? null : employeeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.DepartmentID
     *
     * @return the value of fruser.DepartmentID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.DepartmentID
     *
     * @param departmentid the value for fruser.DepartmentID
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setDepartmentid(String departmentid) {
        this.departmentid = departmentid == null ? null : departmentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.CreateTime
     *
     * @return the value of fruser.CreateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.CreateTime
     *
     * @param createtime the value for fruser.CreateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Password
     *
     * @return the value of fruser.Password
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Password
     *
     * @param password the value for fruser.Password
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Salt
     *
     * @return the value of fruser.Salt
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Salt
     *
     * @param salt the value for fruser.Salt
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Activity
     *
     * @return the value of fruser.Activity
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Boolean getActivity() {
        return activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Activity
     *
     * @param activity the value for fruser.Activity
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setActivity(Boolean activity) {
        this.activity = activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.EmailActivity
     *
     * @return the value of fruser.EmailActivity
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Boolean getEmailactivity() {
        return emailactivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.EmailActivity
     *
     * @param emailactivity the value for fruser.EmailActivity
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setEmailactivity(Boolean emailactivity) {
        this.emailactivity = emailactivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.PhoneActivity
     *
     * @return the value of fruser.PhoneActivity
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Boolean getPhoneactivity() {
        return phoneactivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.PhoneActivity
     *
     * @param phoneactivity the value for fruser.PhoneActivity
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setPhoneactivity(Boolean phoneactivity) {
        this.phoneactivity = phoneactivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Email
     *
     * @return the value of fruser.Email
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Email
     *
     * @param email the value for fruser.Email
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Phone
     *
     * @return the value of fruser.Phone
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Phone
     *
     * @param phone the value for fruser.Phone
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Status
     *
     * @return the value of fruser.Status
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Status
     *
     * @param status the value for fruser.Status
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.UpdateTime
     *
     * @return the value of fruser.UpdateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.UpdateTime
     *
     * @param updatetime the value for fruser.UpdateTime
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Updater
     *
     * @return the value of fruser.Updater
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Updater
     *
     * @param updater the value for fruser.Updater
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.AuditDate
     *
     * @return the value of fruser.AuditDate
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Date getAuditdate() {
        return auditdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.AuditDate
     *
     * @param auditdate the value for fruser.AuditDate
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setAuditdate(Date auditdate) {
        this.auditdate = auditdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Audited
     *
     * @return the value of fruser.Audited
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Boolean getAudited() {
        return audited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Audited
     *
     * @param audited the value for fruser.Audited
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setAudited(Boolean audited) {
        this.audited = audited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Type
     *
     * @return the value of fruser.Type
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Type
     *
     * @param type the value for fruser.Type
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.Number
     *
     * @return the value of fruser.Number
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.Number
     *
     * @param number the value for fruser.Number
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.FrontImage
     *
     * @return the value of fruser.FrontImage
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getFrontimage() {
        return frontimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.FrontImage
     *
     * @param frontimage the value for fruser.FrontImage
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setFrontimage(String frontimage) {
        this.frontimage = frontimage == null ? null : frontimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.BackImage
     *
     * @return the value of fruser.BackImage
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getBackimage() {
        return backimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.BackImage
     *
     * @param backimage the value for fruser.BackImage
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setBackimage(String backimage) {
        this.backimage = backimage == null ? null : backimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.DurDate
     *
     * @return the value of fruser.DurDate
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public Date getDurdate() {
        return durdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.DurDate
     *
     * @param durdate the value for fruser.DurDate
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setDurdate(Date durdate) {
        this.durdate = durdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.enFirstName
     *
     * @return the value of fruser.enFirstName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getEnfirstname() {
        return enfirstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.enFirstName
     *
     * @param enfirstname the value for fruser.enFirstName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setEnfirstname(String enfirstname) {
        this.enfirstname = enfirstname == null ? null : enfirstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the footstone column fruser.enLastName
     *
     * @return the value of fruser.enLastName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public String getEnlastname() {
        return enlastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the footstone column fruser.enLastName
     *
     * @param enlastname the value for fruser.enLastName
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    public void setEnlastname(String enlastname) {
        this.enlastname = enlastname == null ? null : enlastname.trim();
    }
    
    private List<Role> roleList;
    private List<Permission> permissionList;

	public List<Role> getRoleList() {
		return roleList;
	}

	public void setRoleList(List<Role> roleList) {
		this.roleList = roleList;
	}

	public List<Permission> getPermissionList() {
		return permissionList;
	}

	public void setPermissionList(List<Permission> permissionList) {
		this.permissionList = permissionList;
	}
    
}