package com.beiyelin.service.footstone.dao;

import com.beiyelin.service.footstone.model.Organization;

public interface OrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frorg
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frorg
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int insert(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frorg
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int insertSelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frorg
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    Organization selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frorg
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int updateByPrimaryKeySelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frorg
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int updateByPrimaryKey(Organization record);
}