package com.beiyelin.service.footstone.dao;

import java.util.List;

import com.beiyelin.service.footstone.model.Permission;

public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frpermission
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frpermission
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frpermission
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frpermission
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    Permission selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frpermission
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frpermission
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frpermission
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int updateByPrimaryKey(Permission record);
    
    List<Permission> selectPermissionsByUserPrimaryKey(String id);
    List<Permission> selectPermissionsByUserCode(String userCode);
    List<Permission> selectPermissionsByRolePrimaryKey(String id);
    List<Permission> selectDefaultOrganizationPermissionsByRoleCode(String roleCode);
    
}