package com.beiyelin.service.footstone.dao;

import com.beiyelin.service.footstone.model.RolePermission;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frrolepermission
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frrolepermission
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int insert(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frrolepermission
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int insertSelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frrolepermission
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    RolePermission selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frrolepermission
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int updateByPrimaryKeySelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frrolepermission
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int updateByPrimaryKey(RolePermission record);
    
    int deleteRolePermissionByRolePrimaryKey(String id);
}