package com.beiyelin.service.footstone.dao;

import java.util.List;

import com.beiyelin.service.footstone.model.Role;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frrole
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frrole
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frrole
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frrole
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    Role selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frrole
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table frrole
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int updateByPrimaryKey(Role record);
    
    List<Role> selectRolesByUserPrimaryKey(String id);
    List<Role> selectRolesByUserCode(String userCode);
    
}