package com.beiyelin.service.footstone.dao;

import com.beiyelin.service.footstone.model.TestUser;
import java.util.List;

public interface TestUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table user
     *
     * @mbggenerated Sat Oct 01 16:27:39 CST 2016
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table user
     *
     * @mbggenerated Sat Oct 01 16:27:39 CST 2016
     */
    int insert(TestUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table user
     *
     * @mbggenerated Sat Oct 01 16:27:39 CST 2016
     */
    TestUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table user
     *
     * @mbggenerated Sat Oct 01 16:27:39 CST 2016
     */
    List<TestUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table user
     *
     * @mbggenerated Sat Oct 01 16:27:39 CST 2016
     */
    int updateByPrimaryKey(TestUser record);
}