package com.beiyelin.service.footstone.dao;

import com.beiyelin.service.footstone.model.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table fruser
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table fruser
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table fruser
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table fruser
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table fruser
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the footstone table fruser
     *
     * @mbg.generated Sun Sep 25 21:06:02 CST 2016
     */
    int updateByPrimaryKey(User record);
}